#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

npx --no-install commitlint --edit "$1"

# Format and submit code according to lintstagedrc.js configuration
# npm run lint:lint-staged

# exit 1 # Commit will be aborted
